//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otelwebsitesi.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Otelwebsitesi.App_GlobalResources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string adres {
            get {
                return ResourceManager.GetString("adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        internal static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizi takip edin.
        /// </summary>
        internal static string bizitakipedin {
            get {
                return ResourceManager.GetString("bizitakipedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyurularımız.
        /// </summary>
        internal static string duyurulamiz {
            get {
                return ResourceManager.GetString("duyurulamiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string giris {
            get {
                return ResourceManager.GetString("giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncellemeler için abone ol.
        /// </summary>
        internal static string güncellemeler {
            get {
                return ResourceManager.GetString("güncellemeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        internal static string hakkimizda {
            get {
                return ResourceManager.GetString("hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        internal static string iletisim {
            get {
                return ResourceManager.GetString("iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnsan Kaynakları.
        /// </summary>
        internal static string insankaynaklari {
            get {
                return ResourceManager.GetString("insankaynaklari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampayalarımız.
        /// </summary>
        internal static string kampanyalarimiz {
            get {
                return ResourceManager.GetString("kampanyalarimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanyalarımızı detaylı görmek için tıklayınız.
        /// </summary>
        internal static string kampanyalarimizigörünüz {
            get {
                return ResourceManager.GetString("kampanyalarimizigörünüz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt ol.
        /// </summary>
        internal static string kayit {
            get {
                return ResourceManager.GetString("kayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kısayollarımız.
        /// </summary>
        internal static string kısayollarimiz {
            get {
                return ResourceManager.GetString("kısayollarimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Adresimiz.
        /// </summary>
        internal static string mailadresimiz {
            get {
                return ResourceManager.GetString("mailadresimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odalar.
        /// </summary>
        internal static string odalar {
            get {
                return ResourceManager.GetString("odalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restuarant&amp;Bar.
        /// </summary>
        internal static string resbar {
            get {
                return ResourceManager.GetString("resbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervasyon.
        /// </summary>
        internal static string rezervasyon {
            get {
                return ResourceManager.GetString("rezervasyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salonlarımız.
        /// </summary>
        internal static string salonlarimiz {
            get {
                return ResourceManager.GetString("salonlarimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Numaramız.
        /// </summary>
        internal static string telefonnumarasi {
            get {
                return ResourceManager.GetString("telefonnumarasi", resourceCulture);
            }
        }
    }
}
