//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otelwebsitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class hakkimizda
    {
        public int hakkimizdaID { get; set; }
        public string hakkimizdaBilgi { get; set; }
        public string hakkimizdaResim { get; set; }
        public string hakkimizdaBaslik { get; set; }
        public string hakkimizdasatir1 { get; set; }
        public string hakkimizdasatir2 { get; set; }
        public string hakkimizdasatir3 { get; set; }
        public string hakkimizdasatir4 { get; set; }
        public string hakkimizdasatir5 { get; set; }
        public string hakkimizdasatir6 { get; set; }
        public string hakkimizdasatir7 { get; set; }
        public string hakkimizdasatir8 { get; set; }
        public string hakkimizdasatir9 { get; set; }
        public string hakkimizdaBaslik1 { get; set; }
        public string hakkimizdaBilgi1 { get; set; }
        public string hakkimizdaBilgi2 { get; set; }
        public string hakkimizdaBaslik2 { get; set; }
        public string hakkimizdaBaslik3 { get; set; }
        public string hakkimizdaBilgi3 { get; set; }
        public string hakkimizdaBaslik4 { get; set; }
        public string hakkimizdaBilgi4 { get; set; }
        public string hakkimizdaBaslik5 { get; set; }
        public string hakkimizdaBilgi5 { get; set; }
    }
}
