//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otelwebsitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class insankaynaklari
    {
        public int ikID { get; set; }
        public string ikResim { get; set; }
        public string ikBaslik { get; set; }
        public string ikBaslik1 { get; set; }
        public string ikBaslik3 { get; set; }
        public string ikBaslik4 { get; set; }
        public string ikBilgi { get; set; }
        public string ikBilgi1 { get; set; }
        public string ikBilgi2 { get; set; }
        public string ikBilgi3 { get; set; }
        public string ikBilgi4 { get; set; }
        public string ikBilgi5 { get; set; }
        public string ikBilgi6 { get; set; }
        public string ikBilgi7 { get; set; }
        public string ikBilgi8 { get; set; }
        public string ikBilgi9 { get; set; }
    
        public virtual insankaynaklaridetay insankaynaklaridetay { get; set; }
    }
}
