//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otelwebsitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restuarant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restuarant()
        {
            this.restuarantdetay = new HashSet<restuarantdetay>();
        }
    
        public int restuarantID { get; set; }
        public string restuarantResim { get; set; }
        public string restuarantBilgi { get; set; }
        public string resim2 { get; set; }
        public string resim3 { get; set; }
        public string resim4 { get; set; }
        public string resim5 { get; set; }
        public string resim6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<restuarantdetay> restuarantdetay { get; set; }
    }
}
