//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otelwebsitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezervasyonumuz
    {
        public int rezervasyonID { get; set; }
        public string giristarihi { get; set; }
        public string cikistarihi { get; set; }
        public int yetiskinsayisi { get; set; }
        public string Ad { get; set; }
        public string Soyadı { get; set; }
        public Nullable<int> TelefonNumarasi { get; set; }
        public string Eposta { get; set; }
        public string Adresiniz { get; set; }
        public Nullable<int> odalarID { get; set; }
        public Nullable<int> uyeID { get; set; }
        public string odaTürü { get; set; }
        public string odaKat { get; set; }
    
        public virtual odalarımız odalarımız { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
