//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otelwebsitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salonlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salonlar()
        {
            this.salonlarimizdetay = new HashSet<salonlarimizdetay>();
        }
    
        public int salonlarID { get; set; }
        public string salonResmi { get; set; }
        public string salonBilgi { get; set; }
        public string salonBaslik { get; set; }
        public string salonbilgisatiri1 { get; set; }
        public string salonbilgisatiri2 { get; set; }
        public string salonbilgisatiri3 { get; set; }
        public string salonbilgisatiri4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salonlarimizdetay> salonlarimizdetay { get; set; }
    }
}
