//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otelwebsitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class sliderbilgi
    {
        public int sliderbilgiID { get; set; }
        public string sliderfoto1 { get; set; }
        public string sliderfoto2 { get; set; }
        public string sliderfoto3 { get; set; }
        public string sliderfoto4 { get; set; }
        public string slidertext1 { get; set; }
        public string slidertext2 { get; set; }
        public string slidertext3 { get; set; }
        public string slidertext4 { get; set; }
        public string kategori { get; set; }
    }
}
