//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otelwebsitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class odalardetay
    {
        public int odalardetayID { get; set; }
        public string odalardetayBilgi { get; set; }
        public Nullable<int> dil { get; set; }
        public Nullable<int> odalarID { get; set; }
    
        public virtual odalarımız odalarımız { get; set; }
    }
}
