//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otelwebsitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class odalarımız
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public odalarımız()
        {
            this.odalardetay = new HashSet<odalardetay>();
            this.rezervasyonumuz = new HashSet<rezervasyonumuz>();
        }
    
        public int odalarID { get; set; }
        public string odaTürü { get; set; }
        public Nullable<int> odaKat { get; set; }
        public string odaBilgi { get; set; }
        public Nullable<int> kalanOdasayisi { get; set; }
        public Nullable<int> odaÜcreti { get; set; }
        public string genelodadetayi { get; set; }
        public string odaResim { get; set; }
        public string basliklar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<odalardetay> odalardetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rezervasyonumuz> rezervasyonumuz { get; set; }
    }
}
